version: '3.8'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    container_name: ${APP_NAME}-nest
    env_file:
      - .env.docker
    restart: always
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network
    environment:
      DB_HOST: db

volumes:
  pgdata:

networks:
  network:
    driver: bridge
